### ISSUE TITLE
save sip data to db

### ISSUE THREAD

**Issue by darkworks** [ymartineau/peers#15]
am working with pee-gui project and using it in my project, its save account data to conf/peer.xml file and read from it , i want to modify it that it save data to sqlite database . so for that i need help that how to start so that i can pass directly username , host , password etc to it . 

thanks

**Comment by ymartineau** [comment]
Take a look at peers-gui event manager register method. You should create a
config subclass or implementation and use this object as user agent
constructor parameter.
