### ISSUE TITLE
how to set caller ID

### ISSUE THREAD

**Issue by darkworks** [ymartineau/peers#16]
i want to know how can we set caller ID , like display name which appear on  receiver side when call is made

**Comment by ymartineau** [comment]
in sip messages, you have headers, one of them is From
From: "John McEnroe" <john.mcenroe@tennis.org>

sometimes sip phones display the "display name" (here "John McEnroe") and
not the sip uri (john.mcenroe@tennis.org).

in peers you can modifiy the sip uri in peers.xml and you can modify the
display name manually using a custom uri in UAC:132 invite method
(profileUri). You cannot modify it only from event manager only.

**Comment by darkworks** [comment]
thanks , i will look into it
