### ISSUE TITLE
Simple use without GUI

### ISSUE THREAD

**Issue by heruan** [ymartineau/peers#31]
I'm a little bit lost here, I see examples for Swing, JWS, etc. but I can't find an example for a simple use case as: *place a call and playback an audio stream*. Can I have a little help for this?

I have an Asterisk server on localhost, I've created a "peers:1234" user and I have a *message.wav* file. How can I simply call an extension, say "400", and play the file? No GUI, just a simple `main` executable.

Thank you!

**Comment by ymartineau** [comment]
Hi,

did you check the peers-demo project ? It might be easier to start with
this one.

https://github.com/ymartineau/peers/tree/master/peers-demo

Then check the <mediaMode> and <mediaFile> parameters in peers.xml config
file to understand how to use them and use hard coded values in
CustomConfig peers-demo class to "replace" values from config file in
getMediaFile and getMediaMode.

Then, if you don't  need the interactive command line interface, you can
update Event Manager to perform different actions.

That said,  don't expect anyone to solve problems for you...

Thank you for using peers,

Yohann

Le 24 févr. 2017 22:47, "Giovanni Lovato" <notifications@github.com> a
écrit :

**Comment by heruan** [comment]
Thank you @ymartineau for the response! Don't get me wrong, I'm not asking to solve any problem just looking for a hint on using a this library. I read the demo and the documentation but I'm still confused: I'm able to register the `UserAgent` and sending invites, then reacting on `calleePickup`. I'm stuck here: what is the right way to playback an audio stream when the callee picks up?

**Comment by heruan** [comment]
I've came up with this:

```java
@Override
public void calleePickup(SipResponse sipResponse) {
    SDPManager sdpManager = new SDPManager(this.agent, LOGGER);
    SessionDescription sessionDescription = sdpManager.parse(sipResponse.getBody());
    MediaDestination mediaDestination = sdpManager.getMediaDestination(sessionDescription);
    String destination = mediaDestination.getDestination();
    int port = mediaDestination.getPort();
    Codec codec = mediaDestination.getCodec();
    DatagramSocket datagramSocket = null;
    int rtpPort = this.agent.getConfig().getRtpPort();
    if (rtpPort == 0) {
        int localPort = -1;
        while (localPort % 2 != 0) {
            datagramSocket = new DatagramSocket();
            localPort = datagramSocket.getLocalPort();
            if (localPort % 2 != 0) {
                datagramSocket.close();
            }
        }
    } else {
        datagramSocket = new DatagramSocket(rtpPort);
    }
    RtpSession rtpSession = new RtpSession(this.agent.getConfig().getLocalInetAddress(), datagramSocket, false,  LOGGER, HOME);
    rtpSession.setRemoteAddress(InetAddress.getByName(destination));
    rtpSession.setRemotePort(port);
    SoundSource soundSource = new FileReader(FILENAME, DataFormat.DEFAULT, LOGGER);
    CaptureRtpSender rtpSender = new CaptureRtpSender(rtpSession, soundSource, false, codec, LOGGER, HOME);
    rtpSender.start();
}
```
