### ISSUE TITLE
There is a Hold Music always

### ISSUE THREAD

**Issue by MehdiRaza1998** [ymartineau/peers#43]
In my case, call is successfully received on my cellphone, but when I pick the call, it always rings a hold music. 
Kindly help

**Comment by ymartineau** [comment]
hi,

can you share network traffic capture? e.g. using wireshark or tcpdump

thank you

yohann

Le lun. 14 déc. 2020 à 13:29, Mehdi Raza Lakho <notifications@github.com> a
écrit :

**Comment by MehdiRaza1998** [comment]
Wait, this made me think of what value should I keep on the IpAddress tag in xml file? because at the moment I have placed there 0.0.0.0, can this be issue?

**Comment by MehdiRaza1998** [comment]
Wow, this issue solved by just keeping the Ipaddress tag empty 
<ipAddress/>
like this!
Thanks for the idea of network traffic!

**Comment by MehdiRaza1998** [comment]
Solved!
