### ISSUE TITLE
DTMF packets have different timestamps

### ISSUE THREAD

**Issue by legate** [ymartineau/peers#7]
It seems DTMF packets have increasing timestamps. My packet analyzer shows that a DTMF digit is sent as 6 RTP event packets, however these packets have both increasing timestamps and durations. I noticed this issue when calling into my SIP provider; I entered a single DTMF digit "2" which was interpreted as "222222" on the other side of the line. I believe the standard specifies that DTMF update packets should have the same timestamp as the initial packet: https://tools.ietf.org/html/rfc4733#section-2.5.1.2

**Comment by ymartineau** [comment]
i'm afraid you're right.
In RtpSender, the timestamp is increased, be it a dtmf packet (pushed
packet) or a standard audi opacket:

https://github.com/ymartineau/peers/blob/master/peers-lib/src/main/java/net/sourceforge/peers/media/RtpSender.java#L148

here i should find a trick to keep the original timestamp if is a dtmf
packet.

I'll put it in my TODO list but don't expect it to be fixed soon. I'm going
out for vacation.
That said you can propose a fix and send a pull request :)

thanks for reporting,

yohann

**Comment by ymartineau** [comment]
fixed by https://github.com/ymartineau/peers/commit/48420dd8dde2c6bd3479f244e81d4163aebaa3e0
